"""Restaurant video prototype validation tools."""

from .deepseek_client import DeepSeekClient, DeepSeekClientError, MissingDeepSeekAPIKey
from .models import (
    ImageFile,
    PipelineReport,
    PipelineStep,
    PreflightReport,
    ProjectConfig,
    RenderParameterRecommendation,
    Shot,
    ShotPlan,
    Storyboard,
    StoryboardScene,
    TimingRecommendation,
    ValidationIssue,
    ValidationReport,
)
from .pipeline import (
    create_output_dir,
    load_project_json,
    normalize_planner,
    pipeline_report_to_dict,
    run_pipeline,
    scan_image_files,
    write_pipeline_report,
    write_storyboard,
)
from .preflight import (
    build_shot_plan,
    estimate_narration_duration,
    preflight_report_to_dict,
    recommend_clip_duration,
    recommend_webui_params,
    run_preflight,
    validate_timing_coverage,
    write_preflight_report,
)
from .storyboard_planner import (
    build_deepseek_storyboard,
    build_mock_storyboard,
    compute_scene_durations,
    identify_image_role,
)
from .validator import report_to_dict, validate_project, write_report

__all__ = [
    "DeepSeekClient",
    "DeepSeekClientError",
    "ImageFile",
    "MissingDeepSeekAPIKey",
    "PipelineReport",
    "PipelineStep",
    "PreflightReport",
    "ProjectConfig",
    "RenderParameterRecommendation",
    "Shot",
    "ShotPlan",
    "Storyboard",
    "StoryboardScene",
    "TimingRecommendation",
    "ValidationIssue",
    "ValidationReport",
    "build_mock_storyboard",
    "build_shot_plan",
    "build_deepseek_storyboard",
    "compute_scene_durations",
    "create_output_dir",
    "estimate_narration_duration",
    "identify_image_role",
    "load_project_json",
    "normalize_planner",
    "pipeline_report_to_dict",
    "preflight_report_to_dict",
    "recommend_clip_duration",
    "recommend_webui_params",
    "report_to_dict",
    "run_pipeline",
    "run_preflight",
    "scan_image_files",
    "validate_timing_coverage",
    "validate_project",
    "write_pipeline_report",
    "write_preflight_report",
    "write_report",
    "write_storyboard",
]
