"""Restaurant video prototype validation tools."""

from .deepseek_client import DeepSeekClient, DeepSeekClientError, MissingDeepSeekAPIKey
from .models import (
    ImageFile,
    ImageUnderstandingItem,
    ImageUnderstandingReport,
    NarrationLine,
    NarrationPlan,
    PipelineReport,
    PipelineStep,
    PreflightReport,
    ProjectConfig,
    RenderParameterRecommendation,
    Shot,
    ShotPlan,
    Storyboard,
    StoryboardContractIssue,
    StoryboardContractReport,
    StoryboardQualityReport,
    StoryboardScene,
    TimingRecommendation,
    TTSContractReport,
    ValidationIssue,
    ValidationReport,
)
from .image_understanding import (
    build_mock_image_understanding,
    image_understanding_to_dict,
)
from .narration_plan import (
    build_narration_plan,
    estimate_speech_seconds,
    narration_plan_to_dict,
    tts_contract_report_to_dict,
    validate_tts_contract,
)
from .pipeline import (
    create_output_dir,
    load_project_json,
    normalize_planner,
    pipeline_report_to_dict,
    run_pipeline,
    scan_image_files,
    write_narration_plan,
    write_image_understanding,
    write_pipeline_report,
    write_storyboard,
)
from .preflight import (
    build_shot_plan,
    estimate_narration_duration,
    preflight_report_to_dict,
    recommend_clip_duration,
    recommend_webui_params,
    run_preflight,
    validate_timing_coverage,
    write_preflight_report,
)
from .storyboard_planner import (
    build_deepseek_storyboard,
    build_mock_storyboard,
    compute_scene_durations,
    identify_image_role,
)
from .storyboard_contract import (
    storyboard_contract_report_to_dict,
    storyboard_quality_report_to_dict,
    validate_storyboard_contract,
    validate_storyboard_quality_contract,
)
from .validator import report_to_dict, validate_project, write_report

__all__ = [
    "DeepSeekClient",
    "DeepSeekClientError",
    "ImageFile",
    "ImageUnderstandingItem",
    "ImageUnderstandingReport",
    "MissingDeepSeekAPIKey",
    "NarrationLine",
    "NarrationPlan",
    "PipelineReport",
    "PipelineStep",
    "PreflightReport",
    "ProjectConfig",
    "RenderParameterRecommendation",
    "Shot",
    "ShotPlan",
    "Storyboard",
    "StoryboardContractIssue",
    "StoryboardContractReport",
    "StoryboardQualityReport",
    "StoryboardScene",
    "TimingRecommendation",
    "TTSContractReport",
    "ValidationIssue",
    "ValidationReport",
    "build_mock_image_understanding",
    "build_narration_plan",
    "build_mock_storyboard",
    "build_shot_plan",
    "build_deepseek_storyboard",
    "compute_scene_durations",
    "create_output_dir",
    "estimate_narration_duration",
    "estimate_speech_seconds",
    "identify_image_role",
    "image_understanding_to_dict",
    "load_project_json",
    "normalize_planner",
    "narration_plan_to_dict",
    "pipeline_report_to_dict",
    "preflight_report_to_dict",
    "recommend_clip_duration",
    "recommend_webui_params",
    "report_to_dict",
    "run_pipeline",
    "run_preflight",
    "scan_image_files",
    "validate_timing_coverage",
    "validate_project",
    "validate_storyboard_contract",
    "validate_storyboard_quality_contract",
    "validate_tts_contract",
    "write_pipeline_report",
    "write_preflight_report",
    "write_image_understanding",
    "write_narration_plan",
    "write_report",
    "write_storyboard",
    "storyboard_contract_report_to_dict",
    "storyboard_quality_report_to_dict",
    "tts_contract_report_to_dict",
]
