from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
from typing import Any

from .models import ImageFile, ImageUnderstandingItem, ImageUnderstandingReport


MOCK_IMAGE_UNDERSTANDING_VERSION = "mock-image-understanding-v1"

INVALID_NAME_HINTS = {
    "qrcode": "invalid_qrcode",
    "qr": "invalid_qrcode",
    "phone": "invalid_phone",
    "tel": "invalid_phone",
    "address": "invalid_address",
    "menu": "invalid_menu",
    "price": "invalid_price",
    "contact": "invalid_contact",
    "wechat": "invalid_wechat",
    "wx": "invalid_wechat",
}

TYPE_KEYWORDS = (
    ("intro", ("intro", "storefront", "front", "sign", "door")),
    ("interior", ("interior", "inside", "room", "hall", "environment")),
    ("dish", ("dish_1", "dish1", "dish_2", "dish_3", "dish", "food", "cuisine", "meal")),
    ("dining", ("dining", "gathering", "table", "friends", "family")),
    ("detail", ("detail", "sauce", "soup", "pot", "ingredient")),
    ("extra", ("extra",)),
    ("logo", ("logo",)),
)

TYPE_SCORES = {
    "intro": (0.75, 0.85, 0.75, 0.05),
    "interior": (0.75, 0.55, 0.80, 0.05),
    "dish": (0.80, 0.90, 0.85, 0.05),
    "dining": (0.75, 0.65, 0.85, 0.05),
    "detail": (0.65, 0.55, 0.65, 0.10),
    "extra": (0.65, 0.55, 0.65, 0.10),
    "logo": (0.55, 0.40, 0.35, 0.25),
    "other": (0.65, 0.55, 0.65, 0.10),
}
INVALID_SCORES = (0.20, 0.00, 0.00, 0.95)


def build_mock_image_understanding(
    project_id: str,
    image_dir: str | Path,
    image_files: list[ImageFile],
) -> ImageUnderstandingReport:
    images = [
        understand_image_by_filename(index, image)
        for index, image in enumerate(image_files, start=1)
    ]
    category_counts: dict[str, int] = {}
    for item in images:
        category_counts[item.detected_type] = category_counts.get(item.detected_type, 0) + 1

    rejected_images = [item for item in images if not item.allowed_in_video]
    warnings = [
        (
            f"{item.filename} rejected by filename rule as "
            f"{item.detected_type}."
        )
        for item in rejected_images
    ]
    errors: list[str] = []
    if not image_files:
        errors.append("No images found for image understanding.")

    return ImageUnderstandingReport(
        project_id=project_id,
        version=MOCK_IMAGE_UNDERSTANDING_VERSION,
        image_dir=str(Path(image_dir).expanduser().resolve()),
        image_count=len(images),
        allowed_image_count=len(images) - len(rejected_images),
        rejected_image_count=len(rejected_images),
        images=images,
        category_counts=category_counts,
        warnings=warnings,
        errors=errors,
        notes="Generated by filename rule mock. No visual model or OCR was called.",
    )


def understand_image_by_filename(
    image_id: int,
    image: ImageFile,
) -> ImageUnderstandingItem:
    filename = image.name
    lowered = filename.lower()
    detected_type = detect_image_type(lowered)
    allowed_in_video = not detected_type.startswith("invalid_")
    scores = INVALID_SCORES if not allowed_in_video else TYPE_SCORES.get(
        detected_type,
        TYPE_SCORES["other"],
    )
    return ImageUnderstandingItem(
        image_id=image_id,
        filename=filename,
        image_path=str(image.path),
        detected_type=detected_type,
        quality_score=scores[0],
        cover_score=scores[1],
        video_score=scores[2],
        risk_score=scores[3],
        allowed_in_video=allowed_in_video,
        recommended_usage=recommend_usage(detected_type, allowed_in_video),
        recommended_action=recommend_action(detected_type, allowed_in_video),
        reason=build_reason(filename, detected_type, allowed_in_video),
    )


def detect_image_type(lowered_filename: str) -> str:
    for keyword, detected_type in INVALID_NAME_HINTS.items():
        if keyword in lowered_filename:
            return detected_type

    for detected_type, keywords in TYPE_KEYWORDS:
        if any(keyword in lowered_filename for keyword in keywords):
            return detected_type
    return "other"


def recommend_usage(detected_type: str, allowed_in_video: bool) -> str:
    if not allowed_in_video:
        return "reject"
    if detected_type in {"intro", "dish"}:
        return "cover_candidate"
    if detected_type in {"interior", "dining"}:
        return "video_scene"
    return "support"


def recommend_action(detected_type: str, allowed_in_video: bool) -> str:
    if not allowed_in_video:
        return "reject"
    if detected_type in {"other", "logo"}:
        return "review"
    return "use"


def build_reason(
    filename: str,
    detected_type: str,
    allowed_in_video: bool,
) -> str:
    if not allowed_in_video:
        return (
            f"{filename} matched a forbidden filename hint and should be rejected "
            "before video generation."
        )
    if detected_type == "other":
        return (
            f"{filename} did not match a known restaurant category; keep for "
            "manual review."
        )
    return f"{filename} matched filename rule for {detected_type}."


def image_understanding_to_dict(
    report: ImageUnderstandingReport,
) -> dict[str, Any]:
    return asdict(report)
