from __future__ import annotations

import json
import math
from typing import Any

from .deepseek_client import DeepSeekClient
from .models import ImageFile, Storyboard, StoryboardScene


DEFAULT_TARGET_DURATION_SECONDS = 30
MOCK_SCENE_DURATION_SECONDS = 5
SUPPORTED_PLANNERS = {"mock", "deepseek"}


class StoryboardPlannerError(Exception):
    """Raised when a storyboard planner returns invalid output."""


def build_mock_storyboard(
    project_config: dict[str, Any],
    image_files: list[ImageFile],
) -> Storyboard:
    project_id = get_project_id(project_config)
    target_duration_seconds = get_target_duration_seconds(project_config)
    durations = compute_scene_durations(target_duration_seconds, len(image_files))
    scenes = [
        StoryboardScene(
            index=index,
            role=identify_image_role(image.name),
            image_name=image.name,
            image_path=str(image.path),
            mock_duration_seconds=duration,
            mock_narration=(
                f"Mock narration for {identify_image_role(image.name)} scene."
            ),
            notes="mock storyboard only; no AI generation in this phase",
            duration_seconds=duration,
            narration=f"Mock narration for {identify_image_role(image.name)} scene.",
        )
        for index, (image, duration) in enumerate(zip(image_files, durations), start=1)
    ]
    return Storyboard(
        project_id=project_id,
        version="mock-v1",
        scenes=scenes,
        total_mock_duration_seconds=sum(scene.duration_seconds for scene in scenes),
        total_duration_seconds=sum(scene.duration_seconds for scene in scenes),
        notes=(
            "Generated by restaurant_engine pipeline skeleton. No video, TTS, "
            "DeepSeek, or image-to-video service was called."
        ),
    )


def build_deepseek_storyboard(
    project_config: dict[str, Any],
    image_files: list[ImageFile],
    client: DeepSeekClient | None = None,
) -> Storyboard:
    deepseek_client = client or DeepSeekClient()
    messages = build_deepseek_storyboard_messages(project_config, image_files)
    data = deepseek_client.generate_json(messages=messages, temperature=0.2)
    return storyboard_from_deepseek_json(data, project_config, image_files)


def build_deepseek_storyboard_messages(
    project_config: dict[str, Any],
    image_files: list[ImageFile],
) -> list[dict[str, str]]:
    project_id = get_project_id(project_config)
    target_duration_seconds = get_target_duration_seconds(project_config)
    scene_durations = compute_scene_durations(target_duration_seconds, len(image_files))
    payload = {
        "project_id": project_id,
        "restaurant_name": project_config.get("project_name") or project_id,
        "target_duration_seconds": target_duration_seconds,
        "image_count": len(image_files),
        "required_scene_durations_seconds": scene_durations,
        "selected_title": project_config.get("selected_title", ""),
        "user_request": project_config.get("user_request", ""),
        "video_style": project_config.get("video_style", ""),
        "images": [
            {
                "index": index,
                "image_name": image.name,
                "role": identify_image_role(image.name),
            }
            for index, image in enumerate(image_files, start=1)
        ],
    }
    system_prompt = (
        "You are a restaurant short-video storyboard planner. "
        "Return strict JSON only. Do not include markdown, comments, or explanations."
    )
    user_prompt = (
        "Create a storyboard JSON for the supplied restaurant project. "
        "The scenes array length and image_name order must exactly match the images input. "
        "The duration_seconds values must exactly match required_scene_durations_seconds "
        "in order, and total_duration_seconds must equal target_duration_seconds. "
        "Use concise narration suitable for Chinese restaurant promo videos. "
        "Return this JSON object shape: "
        "{"
        '"project_id": string, "version": string, '
        '"scenes": [{"index": number, "role": string, "image_name": string, '
        '"duration_seconds": number, "narration": string, "notes": string}], '
        '"total_duration_seconds": number, "notes": string'
        "}. "
        f"Input: {json.dumps(payload, ensure_ascii=False)}"
    )
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def storyboard_from_deepseek_json(
    data: dict[str, Any],
    project_config: dict[str, Any],
    image_files: list[ImageFile],
) -> Storyboard:
    scenes_data = data.get("scenes")
    if not isinstance(scenes_data, list):
        raise StoryboardPlannerError("DeepSeek storyboard response missing scenes array.")
    if len(scenes_data) != len(image_files):
        raise StoryboardPlannerError(
            "DeepSeek storyboard scene count does not match image count."
        )

    target_duration_seconds = get_target_duration_seconds(project_config)
    durations = compute_scene_durations(target_duration_seconds, len(image_files))
    scenes: list[StoryboardScene] = []
    for expected_index, (scene_data, image) in enumerate(
        zip(scenes_data, image_files),
        start=1,
    ):
        if not isinstance(scene_data, dict):
            raise StoryboardPlannerError("DeepSeek storyboard scene must be an object.")

        image_name = str(scene_data.get("image_name") or "")
        if image_name != image.name:
            raise StoryboardPlannerError(
                "DeepSeek storyboard scene order does not match image order."
            )

        duration = durations[expected_index - 1]
        narration = str(
            scene_data.get("narration")
            or scene_data.get("mock_narration")
            or ""
        )
        scenes.append(
            StoryboardScene(
                index=expected_index,
                role=str(scene_data.get("role") or identify_image_role(image.name)),
                image_name=image_name,
                image_path=str(image.path),
                mock_duration_seconds=duration,
                mock_narration=narration,
                notes=str(
                    scene_data.get("notes")
                    or "generated by DeepSeek planner; duration normalized locally"
                ),
                duration_seconds=duration,
                narration=narration,
            )
        )

    project_id = str(data.get("project_id") or get_project_id(project_config))
    version = str(data.get("version") or "deepseek-v1")
    total_duration = sum(scene.duration_seconds for scene in scenes)

    return Storyboard(
        project_id=project_id,
        version=version,
        scenes=scenes,
        total_mock_duration_seconds=total_duration,
        total_duration_seconds=total_duration,
        notes=str(
            data.get("notes")
            or "Generated by DeepSeek planner. Durations normalized locally."
        ),
    )


def get_project_id(project_config: dict[str, Any]) -> str:
    for key in ("project_id", "project_name", "selected_title"):
        value = str(project_config.get(key) or "").strip()
        if value:
            return value
    return "restaurant_project"


def get_target_duration_seconds(project_config: dict[str, Any]) -> int:
    try:
        target_duration_seconds = int(project_config.get("target_duration_seconds"))
    except (TypeError, ValueError):
        target_duration_seconds = DEFAULT_TARGET_DURATION_SECONDS
    return max(1, target_duration_seconds)


def compute_scene_durations(
    target_duration_seconds: int,
    image_count: int,
) -> list[int]:
    """Distribute target duration across images with integer seconds."""
    if image_count <= 0:
        return []

    target_duration = int(target_duration_seconds or 0)
    if target_duration <= 0:
        return [0 for _ in range(image_count)]

    upper_duration = math.ceil(target_duration / image_count)
    durations = [upper_duration for _ in range(image_count)]
    reductions = upper_duration * image_count - target_duration

    for index in _evenly_spaced_indices(image_count, reductions):
        durations[index] -= 1

    return durations


def _evenly_spaced_indices(length: int, count: int) -> list[int]:
    if length <= 0 or count <= 0:
        return []

    indices: list[int] = []
    used: set[int] = set()
    for step in range(1, count + 1):
        index = math.ceil(step * length / (count + 1)) - 1
        index = min(max(index, 0), length - 1)

        if index in used:
            index = _nearest_unused_index(index, length, used)
        if index is not None:
            indices.append(index)
            used.add(index)
    return indices


def _nearest_unused_index(
    start_index: int,
    length: int,
    used: set[int],
) -> int | None:
    for offset in range(1, length + 1):
        right_index = start_index + offset
        if right_index < length and right_index not in used:
            return right_index

        left_index = start_index - offset
        if left_index >= 0 and left_index not in used:
            return left_index

    return None


def identify_image_role(image_name: str) -> str:
    name = image_name.lower()
    if "intro" in name or "storefront" in name:
        return "intro"
    if "interior" in name:
        return "interior"
    if "dish_1" in name:
        return "dish_1"
    if "dish_2" in name:
        return "dish_2"
    if "dish_3" in name:
        return "dish_3"
    if "dining" in name or "gathering" in name:
        return "dining"
    if "detail" in name:
        return "detail"
    if "extra" in name:
        return "extra"
    return "unknown"


def _coerce_positive_int(value: Any) -> int:
    try:
        number = int(value)
    except (TypeError, ValueError):
        return MOCK_SCENE_DURATION_SECONDS
    return max(1, number)
