from __future__ import annotations

import json
from typing import Any

from .deepseek_client import DeepSeekClient
from .models import ImageFile, Storyboard, StoryboardScene


MOCK_SCENE_DURATION_SECONDS = 5
SUPPORTED_PLANNERS = {"mock", "deepseek"}


class StoryboardPlannerError(Exception):
    """Raised when a storyboard planner returns invalid output."""


def build_mock_storyboard(
    project_config: dict[str, Any],
    image_files: list[ImageFile],
) -> Storyboard:
    project_id = get_project_id(project_config)
    scenes = [
        StoryboardScene(
            index=index,
            role=identify_image_role(image.name),
            image_name=image.name,
            image_path=str(image.path),
            mock_duration_seconds=MOCK_SCENE_DURATION_SECONDS,
            mock_narration=(
                f"Mock narration for {identify_image_role(image.name)} scene."
            ),
            notes="mock storyboard only; no AI generation in this phase",
        )
        for index, image in enumerate(image_files, start=1)
    ]
    return Storyboard(
        project_id=project_id,
        version="mock-v1",
        scenes=scenes,
        total_mock_duration_seconds=sum(
            scene.mock_duration_seconds for scene in scenes
        ),
        notes=(
            "Generated by restaurant_engine pipeline skeleton. No video, TTS, "
            "DeepSeek, or image-to-video service was called."
        ),
    )


def build_deepseek_storyboard(
    project_config: dict[str, Any],
    image_files: list[ImageFile],
    client: DeepSeekClient | None = None,
) -> Storyboard:
    deepseek_client = client or DeepSeekClient()
    messages = build_deepseek_storyboard_messages(project_config, image_files)
    data = deepseek_client.generate_json(messages=messages, temperature=0.2)
    return storyboard_from_deepseek_json(data, project_config, image_files)


def build_deepseek_storyboard_messages(
    project_config: dict[str, Any],
    image_files: list[ImageFile],
) -> list[dict[str, str]]:
    project_id = get_project_id(project_config)
    payload = {
        "project_id": project_id,
        "restaurant_name": project_config.get("project_name") or project_id,
        "target_duration_seconds": project_config.get("target_duration_seconds"),
        "selected_title": project_config.get("selected_title", ""),
        "user_request": project_config.get("user_request", ""),
        "video_style": project_config.get("video_style", ""),
        "images": [
            {
                "index": index,
                "image_name": image.name,
                "role": identify_image_role(image.name),
            }
            for index, image in enumerate(image_files, start=1)
        ],
    }
    system_prompt = (
        "You are a restaurant short-video storyboard planner. "
        "Return strict JSON only. Do not include markdown, comments, or explanations."
    )
    user_prompt = (
        "Create a storyboard JSON for the supplied restaurant project. "
        "The scenes array length and image_name order must exactly match the images input. "
        "Use concise narration suitable for Chinese restaurant promo videos. "
        "Return this JSON object shape: "
        "{"
        '"project_id": string, "version": string, '
        '"scenes": [{"index": number, "role": string, "image_name": string, '
        '"mock_duration_seconds": number, "mock_narration": string, "notes": string}], '
        '"total_mock_duration_seconds": number, "notes": string'
        "}. "
        f"Input: {json.dumps(payload, ensure_ascii=False)}"
    )
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def storyboard_from_deepseek_json(
    data: dict[str, Any],
    project_config: dict[str, Any],
    image_files: list[ImageFile],
) -> Storyboard:
    scenes_data = data.get("scenes")
    if not isinstance(scenes_data, list):
        raise StoryboardPlannerError("DeepSeek storyboard response missing scenes array.")
    if len(scenes_data) != len(image_files):
        raise StoryboardPlannerError(
            "DeepSeek storyboard scene count does not match image count."
        )

    expected_names = [image.name for image in image_files]
    scenes: list[StoryboardScene] = []
    for expected_index, (scene_data, image) in enumerate(
        zip(scenes_data, image_files),
        start=1,
    ):
        if not isinstance(scene_data, dict):
            raise StoryboardPlannerError("DeepSeek storyboard scene must be an object.")

        image_name = str(scene_data.get("image_name") or "")
        if image_name != image.name:
            raise StoryboardPlannerError(
                "DeepSeek storyboard scene order does not match image order."
            )

        duration = _coerce_positive_int(
            scene_data.get("mock_duration_seconds")
            or scene_data.get("duration_seconds")
            or MOCK_SCENE_DURATION_SECONDS
        )
        scenes.append(
            StoryboardScene(
                index=expected_index,
                role=str(scene_data.get("role") or identify_image_role(image.name)),
                image_name=image_name,
                image_path=str(image.path),
                mock_duration_seconds=duration,
                mock_narration=str(scene_data.get("mock_narration") or ""),
                notes=str(scene_data.get("notes") or "generated by DeepSeek planner"),
            )
        )

    project_id = str(data.get("project_id") or get_project_id(project_config))
    version = str(data.get("version") or "deepseek-v1")
    total_duration = data.get("total_mock_duration_seconds") or data.get(
        "total_duration_seconds"
    )
    if total_duration is None:
        total_duration = sum(scene.mock_duration_seconds for scene in scenes)

    return Storyboard(
        project_id=project_id,
        version=version,
        scenes=scenes,
        total_mock_duration_seconds=_coerce_positive_int(total_duration),
        notes=str(data.get("notes") or "Generated by DeepSeek planner."),
    )


def get_project_id(project_config: dict[str, Any]) -> str:
    for key in ("project_id", "project_name", "selected_title"):
        value = str(project_config.get(key) or "").strip()
        if value:
            return value
    return "restaurant_project"


def identify_image_role(image_name: str) -> str:
    name = image_name.lower()
    if "intro" in name or "storefront" in name:
        return "intro"
    if "interior" in name:
        return "interior"
    if "dish_1" in name:
        return "dish_1"
    if "dish_2" in name:
        return "dish_2"
    if "dish_3" in name:
        return "dish_3"
    if "dining" in name or "gathering" in name:
        return "dining"
    if "detail" in name:
        return "detail"
    if "extra" in name:
        return "extra"
    return "unknown"


def _coerce_positive_int(value: Any) -> int:
    try:
        number = int(value)
    except (TypeError, ValueError):
        return MOCK_SCENE_DURATION_SECONDS
    return max(1, number)
